version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_DB: DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - kfet-network

  app:
    image: node:18-bullseye
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run db:migrate && npm run db:seed && npm run build && npm run start"
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://USER:PASSWORD@db:5432/DB
    depends_on:
      - db
    networks:
      - kfet-network

volumes:
  postgres_data:

networks:
  kfet-network:
    driver: bridge
