services:
  db:
    container_name: kfet-db
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data$
    env_file: ".env"
    ports:
      - "5432:5432"
    networks:
      - kfet-network

  app:
    container_name: kfet-app
    build:
      context: .
      dockerfile: Dockerfile.app
    working_dir: /app
    env_file: ".env"
    command: sh -c "npm install && npm run db:deploy && npm run db:seed && npm run build && npm run start"
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - db
    networks:
      - kfet-network

volumes:
  postgres_data:

networks:
  kfet-network:
    driver: bridge
