services:
  db:
    container_name: kfet-db
    image: postgres:15-alpine
    restart: always
    env_file: ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  cache:
    build:
      context: .
      dockerfile: Dockerfile.redis
    restart: always
    volumes:
      - cache:/data
  app:
    container_name: kfet-app
    build:
      context: .
      dockerfile: Dockerfile.app
    restart: always
    working_dir: /app
    env_file: ".env"
    command: sh -c "npm install && npm run db:deploy && npm run build && npm run start"
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres_data:
    name: kfet-postgres-data
  cache:
    name: kfet-cache

