services:
  db:
    container_name: kfet-db
    image: postgres:15-alpine
    env_file: ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  cache:
    image: redis:6.2-alpine
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - cache:/data
    command: ["/bin/sh","-c", "redis-server /etc/redis/redis.conf"]
  app:
    container_name: kfet-app
    image: node:18-bullseye
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npx prisma generate && npm run db:deploy && npm run db:seed && npm run dev"
    ports:
      - "3000:3000"
    env_file: ".env"
    depends_on:
      - db
      - cache

volumes:
  postgres_data:
    name: kfet-postgres-data
  cache:
    name: kfet-cache
